### PR TITLE
Add tests and validations

### PR DESCRIPTION
**Pull request by mwafrika**
## Description

In this project, you will create all controllers and views for your Blog app. As you won't be processing any data yet, you will add simple placeholders for your views with plain HTML.

### General requirements

- [x] Followed the **Github flow**.
- [x] There are no linter errors.
- [x] The documentation is professional.

### JavaScript requirements

- [x] Followed list of [best practices for JavaScript](https://github.com/microverseinc/curriculum-html-css/blob/main/articles/javascript_best_practices.md).

### Project requirements

- [x] Name must not be blank.
- [x] PostsCounter must be an integer greater than or equal to zero.
- [x] Title must not exceed 250 characters.
- [x]  CommentsCounter must be an integer greater than or equal to zero.
- [x]  LikesCounter must be an integer greater than or equal to zero.
- [x]  Add unit specs for all of your models' methods and validations.
- [x]  Add flash messages in the create actions in all your controllers.
- [x]  Make sure that the N+1 problem is solved when fetching all posts and their comments for a user. This is the corresponding wireframe

Thank you for taking the time to review this pull request.

### CODE REVIEW

**Review by AshakaE — CHANGES_REQUESTED** [review]
Hi @mwafrika  , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights


## Required Changes ♻️

- [ ] Kindly use flash messages after save for successful and unsuccessful paths in all controllers
- [ ] Kindly make use of `includes` method to solve `n+1` problem in posts controller

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by mwafrika** [comment]
Thank you for that. 
i am going to work on that

**Review by descholar-ceo — APPROVED** [review]
Hi @mwafrika , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
:+1: Implemented the requested changes changes :heavy_check_mark: 
:+1: Great communication with the reviewer :heavy_check_mark: 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by mwafrika** [comment]
Thank @descholar-ceo

**Pull request merged**
